local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bappewgw-byte/AAAAA/refs/heads/main/library.lua?v=" .. tick()))()

local Window = Library.new({Name = "Generous Hub", GuiName = "GenerousLoader", SubTitle = "Script Loader"})

local FarmPage = Window:CreatePage("Farm Scripts", "wheat")
local FarmSubTab = FarmPage:CreateSubTab("Games")
local FarmCard = FarmSubTab:CreateCard("Available Scripts")

local FPSPage = Window:CreatePage("FPS Scripts", "crosshair")
local FPSSubTab = FPSPage:CreateSubTab("Games")
local FPSCard = FPSSubTab:CreateCard("Available Scripts")

local CasualPage = Window:CreatePage("Casual Scripts", "coffee")
local CasualSubTab = CasualPage:CreateSubTab("Games")
local CasualCard = CasualSubTab:CreateCard("Available Scripts")

local function loadScript(url, name)
    Window:Notify("Loading", "Loading " .. name .. "...", 3, "loader")
    task.wait(1)
    if Window.Destroy then Window.Destroy() end
    loadstring(game:HttpGet(url))()
end

-- FPS
FPSCard:AddButton("Combat Arena", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/combataren", "Combat Arena")
end)
FPSCard:AddButton("Arsenal", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/arsenal", "Arsenal")
end)
FPSCard:AddButton("Violence", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/violence", "Violence")
end)
FPSCard:AddButton("Survive Zombie", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/survivezombie.lua", "Survive Zombie")
end)
FPSCard:AddButton("Spearfish", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/spearfish", "Spearfish")
end)

-- Casual
CasualCard:AddButton("Kawasan Manado", function()
    loadScript("https://pastebin.com/raw/dtiMxrnA", "Kawasan Manado")
end)
CasualCard:AddButton("Mount Kawai", function()
    loadScript("https://pastebin.com/raw/m1X06dqw", "Mount Kawai")
end)
CasualCard:AddButton("Mount Yahayuk", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/yahayuk.lua", "Mount Yahayuk")
end)
CasualCard:AddButton("Mount Daun", function()
    loadScript("https://pastebin.com/raw/KARGQyLa", "Mount Daun")
end)
CasualCard:AddButton("Mount Yntkts", function()
    loadScript("https://pastebin.com/raw/uHrk7xN9", "Mount Yntkts")
end)
CasualCard:AddButton("Mount Aneh", function()
    loadScript("https://pastebin.com/raw/JxcRcN29", "Mount Aneh")
end)
CasualCard:AddButton("Mount Kahayang", function()
    loadScript("https://pastebin.com/raw/TWdFGd8E", "Mount Kahayang")
end)
CasualCard:AddButton("Mount Pengangguran", function()
    loadScript("https://pastebin.com/raw/hVY9miek", "Mount Pengangguran")
end)
CasualCard:AddButton("Mount Perdaunan", function()
    loadScript("https://pastebin.com/raw/nshWv7Z8", "Mount Perdaunan")
end)
CasualCard:AddButton("Mount Baraya", function()
    loadScript("https://pastebin.com/raw/a3WiPdVM", "Mount Baraya")
end)
CasualCard:AddButton("Mount Malaikat", function()
    loadScript("https://pastefy.app/xY9EQHiQ/raw", "Mount Malaikat")
end)
CasualCard:AddButton("Kayak", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/kayak", "Kayak")
end)
CasualCard:AddButton("Dance Now", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/dancnow", "Dance Now")
end)
CasualCard:AddButton("Build A Zoo", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/buildazoo", "Build A Zoo")
end)
CasualCard:AddButton("Layangan", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/layangan.lua", "Layangan")
end)
CasualCard:AddButton("Car Zone", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/CarZone.lua", "Car Zone")
end)
CasualCard:AddButton("Vechycle", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/Vechycle.lua", "Vechycle")
end)
CasualCard:AddButton("QZ", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/QZ.lua", "QZ")
end)

-- Farm
FarmCard:AddButton("Crypto Farm", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/growcrypto", "Crypto Farm")
end)
FarmCard:AddButton("Plants Vs Brainrots", function()
    loadScript("https://pastebin.com/raw/n6hC6NhX", "Plants Vs Brainrots")
end)
FarmCard:AddButton("Fisch Modded", function()
    loadScript("https://pastefy.app/sRKsSxwl/raw", "Fisch Modded")
end)
FarmCard:AddButton("Fish Pet", function()
    loadScript("https://pastefy.app/EQjiFcwK/raw", "Fish Pet")
end)
FarmCard:AddButton("Fish go", function()
    loadScript("https://pastefy.app/OienU9kl/raw", "Fish go")
end)
FarmCard:AddButton("Fisme", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fisme", "Fisme")
end)
FarmCard:AddButton("Getfis", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/getfis", "Getfis")
end)
FarmCard:AddButton("Ikanitu", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/ikanitu", "Ikanitu")
end)
FarmCard:AddButton("Choptree", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/choptree", "Choptree")
end)
FarmCard:AddButton("Fishipe", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishipe", "Fishipe")
end)
FarmCard:AddButton("Fishok", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishok", "Fishok")
end)
FarmCard:AddButton("Mancingyuk", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/mancingyuk", "Mancingyuk")
end)
FarmCard:AddButton("Fishmoded", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishmoded", "Fishmoded")
end)
FarmCard:AddButton("Crystalrenge", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/crystalrenge", "Crystalrenge")
end)
FarmCard:AddButton("Solohunt", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/solohunt", "Solohunt")
end)
FarmCard:AddButton("Mancingcuy", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/mancingcuy", "Mancingcuy")
end)
FarmCard:AddButton("Mancingcuy 2", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/mancingcuy", "Mancingcuy 2")
end)
FarmCard:AddButton("Abyssal", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/abyssal", "Abyssal")
end)
FarmCard:AddButton("Sawahindo", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/sawahindo.lua", "Sawahindo")
end)
FarmCard:AddButton("Horizons", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/horizons.lua", "Horizons")
end)
FarmCard:AddButton("Prospecting", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/prospecting", "Prospecting")
end)
FarmCard:AddButton("Cutgrasss", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/cutgrasss", "Cutgrasss")
end)
FarmCard:AddButton("Catchandtame", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/catchandtame", "Catchandtame")
end)
FarmCard:AddButton("Fishzzza", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishzzza", "Fishzzza")
end)
FarmCard:AddButton("Pointblox", function()
    loadScript("https://raw.githubusercontent.com/generousgamesraw/database/refs/heads/main/pointblox.lua", "Pointblox")
end)
FarmCard:AddButton("Kluckyblok", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/kluckyblok.lua", "Kluckyblok")
end)
FarmCard:AddButton("Slimernge", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/slimernge.lua", "Slimernge")
end)
FarmCard:AddButton("Fido", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fido.lua", "Fido")
end)
FarmCard:AddButton("Buildfarmring", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/buildfarmring.lua", "Buildfarmring")
end)
FarmCard:AddButton("Lemon", function()
    loadScript("https://raw.githubusercontent.com/generousgamesraw/database/refs/heads/main/lemon.lua", "Lemon")
end)
FarmCard:AddButton("Animfishingody", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/animfishingody.lua", "Animfishingody")
end)
FarmCard:AddButton("FishAndMonster", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/FishAndMonster.lua", "FishAndMonster")
end)
FarmCard:AddButton("FindAndMark", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/FindAndMark.lua", "FindAndMark")
end)
FarmCard:AddButton("Storage", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/storage.lua", "Storage")
end)
