local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bappewgw-byte/AAAAA/refs/heads/main/library.lua?v=" .. tick()))()

local Window = Library.new({Name = "Generous Hub", GuiName = "GenerousLoader", SubTitle = "Script Loader"})

local FarmPage = Window:CreatePage("Farm Scripts", "wheat")
local FPSPage = Window:CreatePage("FPS Scripts", "crosshair")
local CasualPage = Window:CreatePage("Casual Scripts", "coffee")

local function loadScript(url, name)
    Window:Notify("Loading", "Loading " .. name .. "...", 3, "loader")
    task.wait(1)
    if Window.Destroy then Window.Destroy() end
    loadstring(game:HttpGet(url))()
end

-- FPS
FPSPage:CreateButton("Combat Arena", "Script for Combat Arena", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/combataren", "Combat Arena")
end)
FPSPage:CreateButton("Arsenal", "Script for Arsenal", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/arsenal", "Arsenal")
end)
FPSPage:CreateButton("Violence", "Script for Violence", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/violence", "Violence")
end)
FPSPage:CreateButton("Survive Zombie", "Script for Survive Zombie", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/survivezombie.lua", "Survive Zombie")
end)
FPSPage:CreateButton("Spearfish", "Script for Spearfish", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/spearfish", "Spearfish")
end)

-- Casual
CasualPage:CreateButton("Kawasan Manado", "Script for Kawasan Manado", "play", function()
    loadScript("https://pastebin.com/raw/dtiMxrnA", "Kawasan Manado")
end)
CasualPage:CreateButton("Mount Kawai", "Script for Mount Kawai", "play", function()
    loadScript("https://pastebin.com/raw/m1X06dqw", "Mount Kawai")
end)
CasualPage:CreateButton("Mount Yahayuk", "Script for Mount Yahayuk", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/yahayuk.lua", "Mount Yahayuk")
end)
CasualPage:CreateButton("Mount Daun", "Script for Mount Daun", "play", function()
    loadScript("https://pastebin.com/raw/KARGQyLa", "Mount Daun")
end)
CasualPage:CreateButton("Mount Yntkts", "Script for Mount Yntkts", "play", function()
    loadScript("https://pastebin.com/raw/uHrk7xN9", "Mount Yntkts")
end)
CasualPage:CreateButton("Mount Aneh", "Script for Mount Aneh", "play", function()
    loadScript("https://pastebin.com/raw/JxcRcN29", "Mount Aneh")
end)
CasualPage:CreateButton("Mount Kahayang", "Script for Mount Kahayang", "play", function()
    loadScript("https://pastebin.com/raw/TWdFGd8E", "Mount Kahayang")
end)
CasualPage:CreateButton("Mount Pengangguran", "Script for Mount Pengangguran", "play", function()
    loadScript("https://pastebin.com/raw/hVY9miek", "Mount Pengangguran")
end)
CasualPage:CreateButton("Mount Perdaunan", "Script for Mount Perdaunan", "play", function()
    loadScript("https://pastebin.com/raw/nshWv7Z8", "Mount Perdaunan")
end)
CasualPage:CreateButton("Mount Baraya", "Script for Mount Baraya", "play", function()
    loadScript("https://pastebin.com/raw/a3WiPdVM", "Mount Baraya")
end)
CasualPage:CreateButton("Mount Malaikat", "Script for Mount Malaikat", "play", function()
    loadScript("https://pastefy.app/xY9EQHiQ/raw", "Mount Malaikat")
end)
CasualPage:CreateButton("Kayak", "Script for Kayak", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/kayak", "Kayak")
end)
CasualPage:CreateButton("Dance Now", "Script for Dance Now", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/dancnow", "Dance Now")
end)
CasualPage:CreateButton("Build A Zoo", "Script for Build A Zoo", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/buildazoo", "Build A Zoo")
end)
CasualPage:CreateButton("Layangan", "Script for Layangan", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/layangan.lua", "Layangan")
end)
CasualPage:CreateButton("Car Zone", "Script for Car Zone", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/CarZone.lua", "Car Zone")
end)
CasualPage:CreateButton("Vechycle", "Script for Vechycle", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/Vechycle.lua", "Vechycle")
end)

-- Farm
FarmPage:CreateButton("Crypto Farm", "Script for Crypto Farm", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/growcrypto", "Crypto Farm")
end)
FarmPage:CreateButton("Plants Vs Brainrots", "Script for Plants Vs Brainrots", "play", function()
    loadScript("https://pastebin.com/raw/n6hC6NhX", "Plants Vs Brainrots")
end)
FarmPage:CreateButton("Fisch Modded", "Script for Fisch Modded", "play", function()
    loadScript("https://pastefy.app/sRKsSxwl/raw", "Fisch Modded")
end)
FarmPage:CreateButton("Fish Pet", "Script for Fish Pet", "play", function()
    loadScript("https://pastefy.app/EQjiFcwK/raw", "Fish Pet")
end)
FarmPage:CreateButton("Fish go", "Script for Fish go", "play", function()
    loadScript("https://pastefy.app/OienU9kl/raw", "Fish go")
end)
FarmPage:CreateButton("Fisme", "Script for Fisme", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fisme", "Fisme")
end)
FarmPage:CreateButton("Getfis", "Script for Getfis", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/getfis", "Getfis")
end)
FarmPage:CreateButton("Ikanitu", "Script for Ikanitu", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/ikanitu", "Ikanitu")
end)
FarmPage:CreateButton("Choptree", "Script for Choptree", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/choptree", "Choptree")
end)
FarmPage:CreateButton("Fishipe", "Script for Fishipe", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishipe", "Fishipe")
end)
FarmPage:CreateButton("Fishok", "Script for Fishok", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishok", "Fishok")
end)
FarmPage:CreateButton("Mancingyuk", "Script for Mancingyuk", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/mancingyuk", "Mancingyuk")
end)
FarmPage:CreateButton("Fishmoded", "Script for Fishmoded", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishmoded", "Fishmoded")
end)
FarmPage:CreateButton("Crystalrenge", "Script for Crystalrenge", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/crystalrenge", "Crystalrenge")
end)
FarmPage:CreateButton("Solohunt", "Script for Solohunt", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/solohunt", "Solohunt")
end)
FarmPage:CreateButton("Mancingcuy", "Script for Mancingcuy", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/mancingcuy", "Mancingcuy")
end)
FarmPage:CreateButton("Mancingcuy 2", "Script for Mancingcuy 2", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/mancingcuy", "Mancingcuy 2")
end)
FarmPage:CreateButton("Abyssal", "Script for Abyssal", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/abyssal", "Abyssal")
end)
FarmPage:CreateButton("Sawahindo", "Script for Sawahindo", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/sawahindo.lua", "Sawahindo")
end)
FarmPage:CreateButton("Horizons", "Script for Horizons", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/horizons.lua", "Horizons")
end)
FarmPage:CreateButton("Prospecting", "Script for Prospecting", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/prospecting", "Prospecting")
end)
FarmPage:CreateButton("Cutgrasss", "Script for Cutgrasss", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/cutgrasss", "Cutgrasss")
end)
FarmPage:CreateButton("Catchandtame", "Script for Catchandtame", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/catchandtame", "Catchandtame")
end)
FarmPage:CreateButton("Fishzzza", "Script for Fishzzza", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fishzzza", "Fishzzza")
end)
FarmPage:CreateButton("Pointblox", "Script for Pointblox", "play", function()
    loadScript("https://raw.githubusercontent.com/generousgamesraw/database/refs/heads/main/pointblox.lua", "Pointblox")
end)
FarmPage:CreateButton("Kluckyblok", "Script for Kluckyblok", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/kluckyblok.lua", "Kluckyblok")
end)
FarmPage:CreateButton("Slimernge", "Script for Slimernge", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/slimernge.lua", "Slimernge")
end)
FarmPage:CreateButton("Fido", "Script for Fido", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/fido.lua", "Fido")
end)
FarmPage:CreateButton("Buildfarmring", "Script for Buildfarmring", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/buildfarmring.lua", "Buildfarmring")
end)
FarmPage:CreateButton("Lemon", "Script for Lemon", "play", function()
    loadScript("https://raw.githubusercontent.com/generousgamesraw/database/refs/heads/main/lemon.lua", "Lemon")
end)
FarmPage:CreateButton("Animfishingody", "Script for Animfishingody", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/animfishingody.lua", "Animfishingody")
end)
FarmPage:CreateButton("FishAndMonster", "Script for FishAndMonster", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/FishAndMonster.lua", "FishAndMonster")
end)
FarmPage:CreateButton("FindAndMark", "Script for FindAndMark", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/FindAndMark.lua", "FindAndMark")
end)
FarmPage:CreateButton("QZ", "Script for QZ", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/QZ.lua", "QZ")
end)
FarmPage:CreateButton("Storage", "Script for Storage", "play", function()
    loadScript("https://raw.githubusercontent.com/bappewgw-byte/FEWFWEF/refs/heads/main/storage.lua", "Storage")
end)
